import { MOTION as T } from './motion';
export type Cue = { role: string; selector: string; at: number; effect?: 'fade' | 'reveal' | 'mask' | 'line' | 'cutout'; duration?: number };
export type Score = { focus: string; decision: string; cues: Cue[] };
const cue = (role: string, selector: string, at: number = T.reveal, effect: Cue['effect'] = 'fade'): Cue => ({ role, selector, at, effect });
const s = (focus: string, decision: string, ...cues: Cue[]): Score => ({ focus, decision, cues });
export const hero = (focus: string): Score => s(focus, 'titulek → cutout fade obrazu → význam',
  cue('tvrzení','[data-hero-title]',T.orient,'reveal'),
  cue('obraz','[data-hero-visual]',T.reveal,'cutout'),
  cue('význam','[data-hero-statement]',T.meaning));
const vision = (focus: string): Score => s(focus,'focus pull: pozadí měkké, portrét doostří',
  cue('tvrzení','[data-hero-title]',T.orient,'reveal'),cue('význam','[data-hero-statement]',T.meaning));
const chapter = (focus: string): Score => s(focus,'portál, číslo, název, čára',
  cue('portál','[data-hero-visual]',0,'cutout'),
  cue('otázka','[data-hero-text]',T.hold,'reveal'),
  cue('číslo kapitoly','[data-chapter-number]',.1,'mask'),
  cue('kapitola','[data-chapter-active]',T.meaning,'line'));
/** Each entry is an authored speaker state, not an animation chosen from DOM order. */
export const score: Record<string, Score> = {
 o1: s('AI mění svět','titul, pak limetková čára pod svět; portál cutout; význam poslední',cue('tvrzení','[data-hero-title]',0,'reveal'),cue('obraz změny','[data-hero-visual]',.2,'cutout'),cue('důraz','[data-title-line]',T.enter,'line'),cue('význam','[data-hero-statement]',T.enter + .22)),
 h1: s('1945 → vstup pro stroj','intro: cifry 0000→1945, osa, budoucí roky; až dojedou, štítky z rohu, pak text'),
 h2: s('1964 → jazyk počítače','cifry rychle → pomalu; až dojedou, cutout fade výřezu'),
 h3: s('1973 → grafické rozhraní','cifry rychle → pomalu; až dojedou, cutout fade výřezu'),
 h4: s('Dnes → Hello! How can I help you today?','nejdřív Dnes, kurzor dvakrát blikne, potom věta',cue('hello','[data-hello-text]',.18)),
 h5: s('Dnes → požadovaný výsledek','Magic Move: Dnes z centra na místo roku, bez rolling cifer; notebook: záměr se mění ve výsledek'),
 i1: s('Poprvé se přizpůsobuje stroj nám','karaoke: 1. věta živá, 2. už pod ní zašedlá, 3. ještě ne'),
 i2: s('A lidé si na to rychle zvykají','Magic Move: 1. ustoupí, 2. převezme velikost, 3. se objeví zašedlá'),
 i3: s('AI už je součástí každodenního života','Magic Move: 2. ustoupí, 3. se zvětší, posune a stane se pointou'),
 a1: s('72 % Čechů','slova, pak glass ze středu, číslo se dopočítá'),
 a2: s('38 % rozhoduje','72 % doleva; glass 38 % ze středu, dopočet'),
 a3: s('63 % porovnává','38 % doleva; glass 63 % ze středu, dopočet'),
 v1: s('5 % vytváří hodnotu','tvrzení → čísla, report cutout fade',cue('tvrzení','[data-hero-title]',T.orient,'reveal'),cue('report','[data-hero-visual]',T.meaning,'cutout')),
 tw1: s('Problém není AI','nejprve věta, poté cutout fade produktů',cue('tvrzení','[data-hero-title]',T.orient,'reveal'),cue('produkty','[data-hero-visual]',T.meaning,'cutout')),
 tw2: s('Svět navržený bez AI','titul ustoupí na kicker; hlavní věta slovo po slově, zalomení jako v PDF'),
 vt0: s('Musíme změnit naše myšlení','stem, pak baterka svítí jedním kuželem',cue('horizont','[data-hero-title]',T.orient,'reveal'),cue('směr','[data-hero-statement]',T.reveal)),
 vi0: s('Existuje několik velkolepých vizí budoucnosti','Magic Move: baterka se rozsvítí do čtyř směrů, text se vymění'),
 vi1: vision('Tělo → kontrola'), vi2: vision('Tempo → adaptace'), vi3: vision('Věda → pochopení'), vi4: vision('Infrastruktura → odpovědnost'),
 c1: s('4 otázky','tvrzení → číslo 4 → karty → od UX / od personalizace / od pozornosti / od kanálů'),
 k1: s('Kdo experience používá?','Magic Move tmavého jádra z karty 01, pak kapitola',
  cue('portál','[data-hero-visual]',0,'cutout'),
  cue('otázka','[data-hero-text]',T.hold,'reveal'),
  cue('číslo kapitoly','[data-chapter-number]',.1,'mask'),
  cue('kapitola','[data-chapter-active]',T.meaning,'line')),
 tr1: s('91 % při designu','slova, pak glass ze středu, číslo se dopočítá'),
 tr1b: s('50 % AI search','91 % doleva; glass 50 % ze středu, dopočet'),
 tr1c: s('1 ze 3 interakcí','50 % doleva; glass 1 ze 3 ze středu, dopočet'),
 ux1: s('Jedna služba, dva uživatelé','nadpis slovo po slově'),
 ux2: s('Člověk / UX','oba glass naráz, vzestup zdola'),
 ux3: s('Agent / AX','UX i AX už jsou; pauza na agenta'),
 un2: s('Need → Outcome','nadpis, persona přijede, pak potřeba projde Need → Context → Intent → Action → Outcome s příkladem u každého kroku'),
 unb: s('Potřeba','Magic Move: kolečko Potřeba se stane obdélníkem, slovo vyroste, uvnitř přivádějí / drží'),
 m1: s('Pochopit','orloj: Pochopit v ohnisku, ostatní menší a rozmazané'),
 m1b: s('Tvořit','orloj se otočí, Tvořit v ohnisku'),
 m1c: s('Rozhodnout','orloj se otočí, Rozhodnout v ohnisku'),
 m1d: s('Konat','orloj se otočí, Konat v ohnisku'),
 m2: s('Čtyři módy','Magic Move: karty se srovnají vedle sebe'),
 ex1: s('Začněte potřebou','titul, pak tři produktové střepy'),
 p0: s('Vibe coding bez PRDu','nadpis → význam → tři teze → dokument'),
 cm1: s('Od KDO k CO','mapa čtyř otázek, zvýraznění z 01 na 02'),
  co1: chapter('Správná zkušenost pro konkrétní situaci'),
  j1: s('Roste očekávání relevance','slova, pak glass ze středu, číslo se dopočítá'),
  j1b: s('Mění se způsob hledání','64 % doleva; glass 25 mld. doprava, dopočet'),
 ad1: s('Ví, co mi sedí.','teniska, pak signály Profil → Potřeba → Chování tečou do produktu, Best match, pak výsledek s 92% shodou'),
 ad2: s('Podle mě. Právě teď.','cesta v čase → moment (persona + kontext) → systém postupně přeplánuje další kroky → pointa'),
  f1: s('Obrazovka jako jednotka designu přestává fungovat','lineární potřeby v nálevce'),
  f2: s('Jednotkou designu se stává potřeba','Magic Move: stejné karty se rozprostřou podle situace'),
  cv1: s('Konverzace je přirozené rozhraní','titul → osa času → řeč až AI dialog → význam'),
  f3: s('Chat není produktová strategie','bridge → robot → psací stroj → tečky načítání → Caesar'),
 ui1: s('UI: výstup dobrý, vstup mizerný','nejdřív nadpis a levá mřížka (dlaždice), pak ale + pravá karta s nezaškrtnutými filtry'),
 ui1k: s('Peklo klikání','až na klik: kurzor bloudí filtry a zaškrtává jeden po druhém, počet produktů klesá, skončí u Zobrazit 711 produktů'),
 ui2: s('AI: vstup dobrý, výstup zeď','nejdřív se dopíše a odešle dotaz, pak chat streamuje zeď textu, která přeteče'),
 ui3b: s('To nejlepší z obou světů','fotka a hlas → dopíše se dotaz → doplňující bublina → limetka → doporučení, srovnání s ukazateli, video a rádce'),
 pa1: s('AI není parťák','obraz se oddálí, pak titul'),
  ha1: s('Tři režimy autonomie','87 % se dopočítá, přijde text, číslo se odsunu a zmenší, pak kompas a tři režimy'),
 vm1: s('Od CO k PROČ VĚŘIT','mapa čtyř otázek, zvýraznění z 02 na 03'),
 ve1: chapter('Proč tomu věřit?'),
 d0: s('Nedůvěra','zjednodušit: ticho, věta, cutout fade obrazu',cue('default','[data-hero-title]',T.hold),cue('porušení','[data-hero-visual]',T.meaning,'cutout')),
 d1: s('60 % pochybuje','slova, pak glass ze středu, číslo se dopočítá'),
 d1b: s('39 % recenze','60 % doleva; glass 39 % ze středu, dopočet'),
 d1c: s('33 % deepfake','39 % doleva; glass 33 % ze středu, dopočet'),
 pr1: s('Značka v zážitku','glass vpravo: billboard + chip Slib.'),
 pr1b: s('Zážitek','klik: kamera z billboardu do obýváku, chip Zážitek.'),
 pr1c: s('Pointa','klik: zoom na celek, Slib získává pozornost / Zkušenost buduje důvěru'),
 pr2: s('AI musí mít důvod','titulek a karta značky, citát čeká na klik'),
 pr2a: s('Slib v uvozovkách','značka napíše slib, čeká na klik'),
 pr2b: s('Neověřitelné','objeví se razítko pod slibem'),
 pr2c: s('Robot','AI vstoupí doprostřed'),
 pr2d: s('AI se ptá','karta vpravo, otázka čeká na klik'),
 pr2f: s('Otázka v uvozovkách','otázka se napíše, čeká na klik'),
 pr2e: s('Potřebuje důkaz','tag pod otázkou'),
 pr3: s('PROVE IT.','magic move: karta AI se ptá na pravou půlku, robot zůstane, otázka zůstane, uvnitř PROVE IT'),
 pr4: s('Dohledatelné důkazy','řádky pod otázkou, skupiny postupně'),
 pr5: s('Najít a ověřit','AI musí zůstane, zbytek titulku se vymění, najít a ověřit je zvýrazněné'),
 pr5b: s('Odjezd důkazu','robot a zelený blok odjedou doleva'),
 pr6: s('Tři bloky','postupně konzistence, odpověď-first, důvěryhodnost'),
 pr6b: s('Labely','uvnitř karet 4 stopy, kde to AI hledá'),
 pr7: s('Fajfka','čáry z karet k ověření'),
 pr8: s('AI najde důvod','pravý blok: důvod vás doporučit'),
 xp1: s('Experience principy','titulek, zvýrazněné Experience principy, čeká na klik'),
 xp1b: s('Produkt','levý horní blok'),
 xp1c: s('Chování lidí','levý dolní blok'),
 xp1d: s('AI Soul & Identity','pravý horní blok'),
 xp1e: s('Digitální design','pravý dolní blok'),
 xp1f: s('Propojení','střed se objeví, čáry k čtyřem blokům'),
 bi1: s('Naše chyby','titulek a portrét, čeká na klik'),
 bi1b: s('Dokonalý student','teze NIST, čeká na klik'),
 bi1c: s('Citát','Reva na střed, citát vpravo po slovech'),
 ts1: s('Tři podmínky důvěry','jen nadpis; karty ještě nejsou',cue('titul','[data-trust-title]',0,'reveal')),
 ts1q: s('Otázka 1','Mohu se na AI spolehnout? se napíše na středu a čeká'),
 ts1a: s('Spolehlivost','otázka se přesune do karty, objeví se Spolehlivost'),
 ts1r: s('Otázka 2','Mám nad AI kontrolu? se napíše na středu a čeká'),
 ts1b: s('Kontrola','otázka se přesune do karty, objeví se Kontrola'),
 ts1s: s('Otázka 3','Co když se něco pokazí? se napíše na středu a čeká'),
 ts1c: s('Náprava','otázka se přesune do karty, objeví se Náprava'),
 ts2: s('Kontrola','magic move: karta Kontrola vyroste, cyklus Human in the Loop se složí sám'),
 jm1: s('Od PROČ VĚŘIT k JAK','mapa čtyř otázek, zvýraznění z 03 na 04'),
 ja1: chapter('Jak musí fungovat firma?'),
 or1: s('78 % firem','slova, pak glass ze středu, číslo se dopočítá'),
 or1b: s('25 % zákazníků','78 % doleva; glass 25 % ze středu, dopočet'),
 or1c: s('85 % vedoucích péče','slova, pak glass ze středu, číslo se dopočítá'),
 or2: s('75 % odmítá handoff','85 % doleva; glass 75 % ze středu, dopočet'),
 ca1: s('Lidé s AI neřeší kanály','titulek ve středu'),
 ca1b: s('Dříve','objeví se dříve'),
 ca1c: s('Pět kanálů','kanály s ikonami postupně vedle sebe'),
 ca2: s('Dnes','dříve odjede pryč, objeví se zákazník a agent'),
 mo1: s('Potřeboval bych refinancovat hypotéku','zákazník napíše záměr a čeká'),
 mo2: s('Agent koordinuje','objeví se AI agent'),
 mo3: s('Celá firma','agent se napojí na data, produkty, procesy, lidi a systémy'),
 mo4: s('Jeden výsledek','výsledek se vrací zákazníkovi'),
 bx0: s('Spojení BX, CX a EX','nejdřív samostatné tvrzení',cue('tvrzení','[data-bx-intro]',T.orient,'reveal')),
 bx1: s('Tři disciplíny. Jedna zkušenost.','tvrzení nahoru; tři bloky se propojí do jedné výsledné experience'),
 vd1: s('Jakub Petřina','featured speaker + fly to dock'),
 vd2: s('Dejan Krstic','park Petřina; feature Dejan'),
 vd3: s('Michaela Edgerley','park Dejan; feature Michaela'),
 vd4: s('Kryštof Maliňák','park Michaela; feature Kryštof'),
 vd5: s('Miloš Nejezchleb','park Kryštof; feature Miloš'),
 vd6: s('Pět hlasů ze stage','park Miloš; all chips lined up'),
 sl1: s('Carousel řečníků','kontinuální průjezd pěti hlasů zleva doprava'),
};

