/** Images each scene shows (recorded from a full deck walk). Used by preload.ts to warm upcoming scenes. */
export const SCENE_IMAGES: Record<string, readonly string[]> = {
  "opening": ["gui.webp", "intent-laptop.webp", "portal.webp", "punch.webp", "terminal.webp"],
  "history": ["gui.webp", "intent-laptop.webp", "portal.webp", "punch.webp", "terminal.webp"],
  "adoption": ["bcg-cover.jpg"],
  "value-gap": ["ai-cutout.webp", "bcg-cover.jpg"],
  "twist": ["ai-cutout.webp"],
  "visions": ["altman.webp", "amodei.webp", "hassabis.webp", "musk.webp"],
  "challenges": ["altman.webp", "amodei.webp", "hassabis.webp", "musk.webp"],
  "trend1": ["ux-ax.webp"],
  "uxax": ["persona-need.png?v=2", "ux-ax.webp"],
  "understanding": ["need-buyer.webp", "need-user.webp", "persona-need.png?v=2"],
  "modes": ["case-cleo.webp?v=5", "case-lemonade.webp?v=5", "case-octopus.webp?v=5", "need-buyer.webp", "need-user.webp"],
  "examples": ["case-cleo.webp?v=5", "case-lemonade.webp?v=5", "case-octopus.webp?v=5", "prd-notebook.webp"],
  "prd": ["prd-notebook.webp"],
  "co": ["portal.webp"],
  "journey": ["portal.webp"],
  "funnel": ["conv-aidialog.png", "conv-messages.png", "conv-symbols.png", "conv-talk.png", "conv-text.png"],
  "conversation": ["caesar.webp?v=full", "chat-robot.png?v=hq", "conv-aidialog.png", "conv-messages.png", "conv-symbols.png", "conv-talk.png", "conv-text.png"],
  "chat": ["caesar.webp?v=full", "chat-robot.png?v=hq", "need-user.jpg"],
  "uiai": ["ai-partner.webp", "need-user.jpg"],
  "partner": ["ai-partner.webp"],
  "verit": ["adapt-mesta.jpg", "adapt-plaze.jpg", "portal.webp"],
  "distrust": ["adapt-mesta.jpg", "adapt-plaze.jpg", "brand-shift.webp", "portal.webp"],
  "prove": ["ai-reason-robot.webp", "brand-shift.webp"],
  "principles": ["ai-reason-robot.webp", "schwartz.webp"],
  "bias": ["schwartz.webp"],
  "jak": ["portal.webp"],
  "orch": ["chat-robot.png", "portal.webp", "tn-user.png"],
  "channels": ["chat-robot.png", "tn-user.png"],
};
