const ts=require('typescript');const fs=require('node:fs');const path=require('node:path');
const root=path.resolve(__dirname,'..');
function load(file){const p=path.resolve(root,file);const m={exports:{}};const code=ts.transpileModule(fs.readFileSync(p,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText;new Function('require','module','exports',code)(name=>load(path.relative(root,path.resolve(path.dirname(p),name+'.ts'))),m,m.exports);return m.exports;}
const {steps}=load('src/deck/deck.ts');const {score}=load('src/engine/choreography.ts');
let text='# Motion audit — Vizionář v době AI\n\n75 stavů, 1920 × 1080. Obsah, fakta, zdroje, speaker notes i pořadí zachovány. Tento dokument popisuje implementovaný motion score, nikoli nový obsah prezentace.\n\n## Aktuální art direction\n\nSvětlý Clientology editorial: šedomodrá plocha, bílé zaoblené plochy, petrolejový text, limetové akcenty. Kombinace fotografických řezů a výrazné typografie, bez celoplošných tmavých slidů. Historické kompozice 1945–1973 zachované, časová osa animuje postup. DNES propojuje zadání s výsledkem ve světlé zaoblené kompozici.\n\n## Jazyk pohybu\n\n- Orientace zůstává okamžitě dostupná v chrome; první význam přichází bez prodlevy nebo po 160ms u kapitoly.\n- Odhalení pracuje s opacity a posunem 12 px. Hero obraz má konečnou masku 680 ms, žádný trvalý parallax.\n- Data mají pevné finální hodnoty; čísla se nepřepočítávají z vymyšlených mezihodnot.\n- Vztahy mají vlastní kresbu trasy podle skutečné délky SVG. Přesun objektů používá stejné uzly.\n- Běžná sekvence končí do 1,4 s. Nový argument vždy vyžaduje zásah speakera.\n- Tiché stavy: mapa keynote, PROVE IT., první věta finále, volitelný film.\n- Reduced motion aplikuje finální stav synchronně.\n- Jediná živá scéna odstranila závod mezi odchozí a příchozí vrstvou. Každý scene score má GSAP context s cleanup.\n\n## Revize jednotlivých stavů\n\n';
for(const [i,step] of steps.entries()){
 const p=score[step.id];text+=`### ${String(i+1).padStart(2,'0')} — ${step.title} (${step.id})\n\nSpeaker moment: ${step.speakerNote}\n\nPrvní pozornost: ${p.focus}.\n\nZásah: ${p.decision}.\n\nOdhalení: ${p.cues.length?p.cues.map(c=>`${c.role} (${Math.round(c.at*1000)} ms, ${c.effect})`).join(' → '):'Vlastní stavová transformace nebo záměrně statický stav podle zásahu výše.'}\n\nNávaznost: ${steps[i-1]?.title||'Vstup do keynote'} → **${step.title}** → ${steps[i+1]?.title||'Konec; bez autoplay'}.\n\n`;
}
text+='## Assety a omezení\n\nAktuální dodaný hero brief předepisuje u 17 pozic existující fotografie nebo grafické kompozice. Všechny tyto kompozice zůstávají v EditorialHero. Volitelný imageSrc umožňuje dodat finální obraz do stejné masky. Nové placené nebo generované assety nebyly přidány. Jediný explicitně chybějící asset je závěrečný film ve stavu 75.\n\nPůvodní obsahové PDF (46 stran) i vizuální PDF (32 stran) byly dostupné a přečtené. Hlavní zdroj aktuálních 75 stavů zůstává deck.ts a REDESIGN_STORYBOARD.md.\n';
fs.writeFileSync(path.join(root,'MOTION_AUDIT.md'),text);
fs.mkdirSync(path.join(root,'validation'),{recursive:true});fs.writeFileSync(path.join(root,'validation/states.json'),JSON.stringify(steps,null,2));
